```puml
@startuml



class Person {
	- Integer id_person
	- String name
	- String surname

	+ Integer getId()
}


class Deal {

	- Integer id_deal
	- Float amount
	- DateTime moment
	- Integer sender
	- Integer receiver
	- String hash
}

Person "1..*" -- "1..*" Deal : to do

@enduml
```